apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2020-02-26T21:10:27Z
    generation: 8
    labels:
      app: jenkins-2-rhel7-credicoop
    name: jenkins-2-rhel7-credicoop
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: jenkins-2-rhel7-credicoop
      deploymentconfig: jenkins-2-rhel7-credicoop
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jenkins-2-rhel7-credicoop
          deploymentconfig: jenkins-2-rhel7-credicoop
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-2-rhel7-credicoop
          imagePullPolicy: Always
          name: jenkins-2-rhel7-credicoop
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: jenkins-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins-2-rhel7-credicoop
        from:
          kind: ImageStreamTag
          name: jenkins-2-rhel7-credicoop:1.0.3
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2020-02-26T21:12:52Z
      lastUpdateTime: 2020-02-26T21:12:52Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    details:
      causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: image-registry.openshift-image-registry.svc:5000/openshift/jenkins-2-rhel7-credicoop
        type: ImageChange
      message: image change
    latestVersion: 7
    observedGeneration: 8
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
